name: Docs
on:
    push:
        branches: [main]
        paths:
            - 'src/**'
            - 'docs/**'
            - '.forgejo/workflows/docs.yml'

jobs:
    deploy:
        name: Build and Deploy Docs
        runs-on: docker

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node v24
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build docs
              run: pnpm docs:build

            - name: Deploy to pages branch
              run: |
                  cd docs/.vitepress/dist
                  git init
                  git config user.name "ci"
                  git config user.email "ci@noreply"
                  git add .
                  git commit -m "deploy docs"
                  git push --force https://oauth2:${{ secrets.DOCS_UPDATE_TOKEN }}@git.gay/nyamelia/djs-localized-builders.git HEAD:pages